### ISSUE TITLE
如何知道具体翻箱过程

### ISSUE THREAD

**Issue by majixin-li** [binarycopycode/CRP_DAM#2]
作者你好，
要知道具体翻箱过程，是设置return_pi=True吗? 但是在decoder.py中并没有定义pi。
此外，还有一些细节问题想请教，不知是否方便留下邮箱。

**Comment by binarycopycode** [comment]
你好，我是从https://github.com/Rintarooo/VRP_DRL_MHA 的代码改过来的，这个工作并没有实现return_pi=True的部分，如果你想在test部分知道具体的翻箱过程，可以在decoder的forward函数的那个for循环中加入记录每一步的action，邮箱是369389379#qq dot com，或者可以直接加我qq
